// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Siged.Infrastructure.Persistence;

#nullable disable

namespace Siged.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260416155720_UpdateGroupJournalsRelation")]
    partial class UpdateGroupJournalsRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PermisoUsuario", b =>
                {
                    b.Property<string>("PermisosEspecialesIdPermiso")
                        .HasColumnType("text");

                    b.Property<int>("UsuariosId")
                        .HasColumnType("integer");

                    b.HasKey("PermisosEspecialesIdPermiso", "UsuariosId");

                    b.HasIndex("UsuariosId");

                    b.ToTable("UsuariosPermisos", (string)null);
                });

            modelBuilder.Entity("RolPermisos", b =>
                {
                    b.Property<string>("PermisosIdPermiso")
                        .HasColumnType("text");

                    b.Property<int>("RolesId")
                        .HasColumnType("integer");

                    b.HasKey("PermisosIdPermiso", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("RolPermisos");

                    b.HasData(
                        new
                        {
                            PermisosIdPermiso = "security.user.view",
                            RolesId = 1
                        },
                        new
                        {
                            PermisosIdPermiso = "security.user.view",
                            RolesId = 2
                        },
                        new
                        {
                            PermisosIdPermiso = "security.user.manage",
                            RolesId = 1
                        },
                        new
                        {
                            PermisosIdPermiso = "security.user.manage",
                            RolesId = 2
                        },
                        new
                        {
                            PermisosIdPermiso = "security.role.view",
                            RolesId = 1
                        },
                        new
                        {
                            PermisosIdPermiso = "security.role.view",
                            RolesId = 2
                        },
                        new
                        {
                            PermisosIdPermiso = "security.role.manage",
                            RolesId = 1
                        },
                        new
                        {
                            PermisosIdPermiso = "security.role.manage",
                            RolesId = 2
                        },
                        new
                        {
                            PermisosIdPermiso = "core.org.view",
                            RolesId = 1
                        },
                        new
                        {
                            PermisosIdPermiso = "core.org.view",
                            RolesId = 2
                        },
                        new
                        {
                            PermisosIdPermiso = "core.org.view",
                            RolesId = 3
                        },
                        new
                        {
                            PermisosIdPermiso = "core.org.view",
                            RolesId = 4
                        },
                        new
                        {
                            PermisosIdPermiso = "core.org.manage",
                            RolesId = 1
                        },
                        new
                        {
                            PermisosIdPermiso = "comp.tourn.view",
                            RolesId = 1
                        },
                        new
                        {
                            PermisosIdPermiso = "comp.tourn.view",
                            RolesId = 2
                        },
                        new
                        {
                            PermisosIdPermiso = "comp.tourn.view",
                            RolesId = 3
                        },
                        new
                        {
                            PermisosIdPermiso = "comp.tourn.view",
                            RolesId = 4
                        },
                        new
                        {
                            PermisosIdPermiso = "comp.tourn.manage",
                            RolesId = 1
                        },
                        new
                        {
                            PermisosIdPermiso = "comp.tourn.manage",
                            RolesId = 3
                        },
                        new
                        {
                            PermisosIdPermiso = "news.view",
                            RolesId = 1
                        },
                        new
                        {
                            PermisosIdPermiso = "news.view",
                            RolesId = 2
                        },
                        new
                        {
                            PermisosIdPermiso = "news.view",
                            RolesId = 3
                        },
                        new
                        {
                            PermisosIdPermiso = "news.create",
                            RolesId = 1
                        },
                        new
                        {
                            PermisosIdPermiso = "news.create",
                            RolesId = 2
                        },
                        new
                        {
                            PermisosIdPermiso = "news.create",
                            RolesId = 3
                        },
                        new
                        {
                            PermisosIdPermiso = "news.manage",
                            RolesId = 1
                        },
                        new
                        {
                            PermisosIdPermiso = "news.manage",
                            RolesId = 2
                        },
                        new
                        {
                            PermisosIdPermiso = "news.highlight",
                            RolesId = 1
                        },
                        new
                        {
                            PermisosIdPermiso = "news.highlight",
                            RolesId = 2
                        });
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Dependencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Siglas")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Dependencias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Oficina de Tecnología de Información",
                            Siglas = "OTI"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Rectorado Central",
                            Siglas = "RECT"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Bienestar Universitario",
                            Siglas = "DBU"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Dirección de Admisión",
                            Siglas = "ADM"
                        });
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Notice.News", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowComments")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowReactions")
                        .HasColumnType("boolean");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Draft");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("News", (string)null);
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Notice.NewsMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("NewsId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NewsId");

                    b.ToTable("NewsMedia");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Organizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abreviatura")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("ColorRepresentativo")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Lema")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PortadaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Facultad");

                    b.HasKey("Id");

                    b.HasIndex("Abreviatura")
                        .IsUnique();

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Organizaciones", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abreviatura = "FIIS",
                            ColorRepresentativo = "#0284c7",
                            EstaActivo = true,
                            Nombre = "Facultad de Ingeniería en Informática y Sistemas",
                            Tipo = "Facultad"
                        },
                        new
                        {
                            Id = 2,
                            Abreviatura = "FZ",
                            ColorRepresentativo = "#d97706",
                            EstaActivo = true,
                            Nombre = "Facultad de Zootecnia",
                            Tipo = "Facultad"
                        },
                        new
                        {
                            Id = 3,
                            Abreviatura = "FA",
                            ColorRepresentativo = "#16a34a",
                            EstaActivo = true,
                            Nombre = "Facultad de Agronomía",
                            Tipo = "Facultad"
                        },
                        new
                        {
                            Id = 4,
                            Abreviatura = "FCEA",
                            ColorRepresentativo = "#9333ea",
                            EstaActivo = true,
                            Nombre = "Facultad de Ciencias Económicas y Administrativas",
                            Tipo = "Facultad"
                        });
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .HasColumnType("text");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("FotoPath")
                        .HasColumnType("text");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DNI")
                        .IsUnique();

                    b.ToTable("Personas", (string)null);

                    b.HasDiscriminator().HasValue("Persona");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Tournaments.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryName")
                        .HasColumnType("text");

                    b.Property<Guid>("DisciplineId")
                        .HasColumnType("uuid");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("TournamentId");

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Tournaments.Discipline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Disciplines");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7f6a5b4c-3d2e-4f0a-9b8c-7d6e5f4a3b2c"),
                            IconUrl = "soccer-ball",
                            IsActive = true,
                            Name = "Fútbol"
                        },
                        new
                        {
                            Id = new Guid("1a2b3c4d-5e6f-4a8b-9c0d-1e2f3a4b5c6d"),
                            IconUrl = "futsal-pitch",
                            IsActive = true,
                            Name = "Futsal"
                        },
                        new
                        {
                            Id = new Guid("b1c2d3e4-f5a6-4b8c-9d0e-1f2a3b4c5d6e"),
                            IconUrl = "volleyball",
                            IsActive = true,
                            Name = "Vóley"
                        },
                        new
                        {
                            Id = new Guid("c1d2e3f4-a5b6-4c8d-9e0f-1a2b3c4d5e6f"),
                            IconUrl = "basketball",
                            IsActive = true,
                            Name = "Básquet"
                        });
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Tournaments.DisciplineRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DisciplineId")
                        .HasColumnType("uuid");

                    b.Property<string>("RuleKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RuleValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId");

                    b.ToTable("DisciplineRules");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9f697f66-8c97-4ceb-968c-46ff30600ea6"),
                            DisciplineId = new Guid("7f6a5b4c-3d2e-4f0a-9b8c-7d6e5f4a3b2c"),
                            RuleKey = "TIENE_TARJETAS",
                            RuleValue = "True"
                        },
                        new
                        {
                            Id = new Guid("95f0062f-3c29-40fc-9393-f024e3e5aac0"),
                            DisciplineId = new Guid("7f6a5b4c-3d2e-4f0a-9b8c-7d6e5f4a3b2c"),
                            RuleKey = "PUNTOS_POR_VICTORIA",
                            RuleValue = "3"
                        },
                        new
                        {
                            Id = new Guid("a4c48254-f27f-4029-aa86-c90f655a77d5"),
                            DisciplineId = new Guid("b1c2d3e4-f5a6-4b8c-9d0e-1f2a3b4c5d6e"),
                            RuleKey = "USA_SETS",
                            RuleValue = "True"
                        },
                        new
                        {
                            Id = new Guid("80ca00c3-9049-4f9f-ae21-0e3b163c3e5a"),
                            DisciplineId = new Guid("b1c2d3e4-f5a6-4b8c-9d0e-1f2a3b4c5d6e"),
                            RuleKey = "PUNTOS_POR_VICTORIA",
                            RuleValue = "2"
                        },
                        new
                        {
                            Id = new Guid("856c97fe-5a58-4fd0-ba30-348637920d15"),
                            DisciplineId = new Guid("c1d2e3f4-a5b6-4c8d-9e0f-1a2b3c4d5e6f"),
                            RuleKey = "CANTIDAD_PERIODOS",
                            RuleValue = "4"
                        });
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Tournaments.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("PhaseId")
                        .HasColumnType("uuid");

                    b.Property<int>("QualifiedCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PhaseId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Tournaments.GroupTeam", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("integer");

                    b.Property<int>("GoalsFor")
                        .HasColumnType("integer");

                    b.Property<bool>("IsQualified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("MatchesDrawn")
                        .HasColumnType("integer");

                    b.Property<int>("MatchesLost")
                        .HasColumnType("integer");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("MatchesWon")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("GroupId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("GroupTeams");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Tournaments.Journal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("PhaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("PhaseId");

                    b.ToTable("Journals");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Tournaments.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DisciplineId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("JournalId")
                        .HasColumnType("uuid");

                    b.Property<int>("LocalScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("LocalTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PhaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("VenueId")
                        .HasColumnType("uuid");

                    b.Property<int>("VisitorScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("VisitorTeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("JournalId");

                    b.HasIndex("LocalTeamId");

                    b.HasIndex("PhaseId");

                    b.HasIndex("VenueId");

                    b.HasIndex("VisitorTeamId");

                    b.ToTable("Matches", (string)null);
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Tournaments.MatchEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("Minute")
                        .HasColumnType("integer");

                    b.Property<int>("Period")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.ToTable("MatchEvents");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Tournaments.Phase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDirectElimination")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.ToTable("Phases");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Tournaments.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEligible")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Tournaments.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Initials")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RepresentativeName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Tournaments.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Organizer")
                        .HasColumnType("text");

                    b.Property<string>("RulesUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Tournaments.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            Id = new Guid("53e29bc9-b236-4a13-b75e-d3a2e1d3b2eb"),
                            Address = "Campus Principal",
                            Capacity = 5000,
                            Name = "Estadio Universitario UNAS"
                        },
                        new
                        {
                            Id = new Guid("79761e43-9a42-4126-9bc3-ca2c53665f33"),
                            Address = "Pabellón de Sistemas",
                            Capacity = 200,
                            Name = "Losa Deportiva FIIS"
                        });
                });

            modelBuilder.Entity("Siged.Domain.Entities.Security.AuditoriaLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detalle")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AuditoriaLogs");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Security.Permiso", b =>
                {
                    b.Property<string>("IdPermiso")
                        .HasColumnType("text");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.HasKey("IdPermiso");

                    b.ToTable("Permisos", (string)null);

                    b.HasData(
                        new
                        {
                            IdPermiso = "security.user.view",
                            Categoria = "SEGURIDAD",
                            Descripcion = "Ver lista de usuarios"
                        },
                        new
                        {
                            IdPermiso = "security.user.manage",
                            Categoria = "SEGURIDAD",
                            Descripcion = "Crear y editar usuarios"
                        },
                        new
                        {
                            IdPermiso = "security.role.view",
                            Categoria = "SEGURIDAD",
                            Descripcion = "Ver roles y permisos"
                        },
                        new
                        {
                            IdPermiso = "security.role.manage",
                            Categoria = "SEGURIDAD",
                            Descripcion = "Gestionar roles y permisos"
                        },
                        new
                        {
                            IdPermiso = "core.org.view",
                            Categoria = "CORE",
                            Descripcion = "Ver facultades y sedes"
                        },
                        new
                        {
                            IdPermiso = "core.org.manage",
                            Categoria = "CORE",
                            Descripcion = "Administrar facultades"
                        },
                        new
                        {
                            IdPermiso = "comp.tourn.view",
                            Categoria = "COMPETENCIAS",
                            Descripcion = "Ver torneos y resultados"
                        },
                        new
                        {
                            IdPermiso = "comp.tourn.manage",
                            Categoria = "COMPETENCIAS",
                            Descripcion = "Gestionar fechas y torneos"
                        },
                        new
                        {
                            IdPermiso = "news.view",
                            Categoria = "NOTICIAS",
                            Descripcion = "Ver gestión de noticias"
                        },
                        new
                        {
                            IdPermiso = "news.create",
                            Categoria = "NOTICIAS",
                            Descripcion = "Crear borradores de noticias"
                        },
                        new
                        {
                            IdPermiso = "news.manage",
                            Categoria = "NOTICIAS",
                            Descripcion = "Publicar, editar y archivar noticias"
                        },
                        new
                        {
                            IdPermiso = "news.highlight",
                            Categoria = "NOTICIAS",
                            Descripcion = "Marcar noticias como destacadas"
                        });
                });

            modelBuilder.Entity("Siged.Domain.Entities.Security.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Control total (OTI)",
                            Nivel = 100,
                            Nombre = "SuperAdmin"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Personal de oficinas centrales",
                            Nivel = 80,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Docente o administrativo de facultad",
                            Nivel = 50,
                            Nombre = "Encargado"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Alumno regular UNAS",
                            Nivel = 10,
                            Nombre = "Estudiante"
                        });
                });

            modelBuilder.Entity("Siged.Domain.Entities.Security.TokenInvalidado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TokensInvalidados");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Security.UserPreference", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("light");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WidgetsVisibles")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("usuarios,orgs,activos,recent");

                    b.HasKey("UserId");

                    b.ToTable("UserPreferences", (string)null);
                });

            modelBuilder.Entity("Siged.Domain.Entities.Security.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreadoPorUsuarioId")
                        .HasColumnType("integer");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("OrganizacionId")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PersonaId")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiereCambioPassword")
                        .HasColumnType("boolean");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPorUsuarioId");

                    b.HasIndex("OrganizacionId");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstaActivo = true,
                            FechaRegistro = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2a$12$eL7jdgl1iOF508ePe1ScyOrYqdzdDedn1yo5WuGrj1E1.ZovUk0Xe",
                            PersonaId = 1,
                            RequiereCambioPassword = false,
                            RolId = 1,
                            Username = "admin_benjamin"
                        },
                        new
                        {
                            Id = 2,
                            EstaActivo = true,
                            FechaRegistro = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2a$12$eL7jdgl1iOF508ePe1ScyOrYqdzdDedn1yo5WuGrj1E1.ZovUk0Xe",
                            PersonaId = 2,
                            RequiereCambioPassword = true,
                            RolId = 2,
                            Username = "apoyo_juan"
                        },
                        new
                        {
                            Id = 3,
                            EstaActivo = true,
                            FechaRegistro = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganizacionId = 1,
                            PasswordHash = "$2a$12$eL7jdgl1iOF508ePe1ScyOrYqdzdDedn1yo5WuGrj1E1.ZovUk0Xe",
                            PersonaId = 3,
                            RequiereCambioPassword = true,
                            RolId = 4,
                            Username = "estudiante_test"
                        },
                        new
                        {
                            Id = 4,
                            EstaActivo = true,
                            FechaRegistro = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganizacionId = 1,
                            PasswordHash = "$2a$12$eL7jdgl1iOF508ePe1ScyOrYqdzdDedn1yo5WuGrj1E1.ZovUk0Xe",
                            PersonaId = 4,
                            RequiereCambioPassword = true,
                            RolId = 3,
                            Username = "encargado_test"
                        });
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Administrador", b =>
                {
                    b.HasBaseType("Siged.Domain.Entities.Core.Persona");

                    b.Property<int?>("DependenciaId")
                        .HasColumnType("integer");

                    b.Property<bool>("EsPersonalInterno")
                        .HasColumnType("boolean");

                    b.HasIndex("DependenciaId");

                    b.HasDiscriminator().HasValue("Administrador");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellidos = "Admin",
                            DNI = "76063362",
                            Nombres = "Benjamín",
                            DependenciaId = 1,
                            EsPersonalInterno = true
                        },
                        new
                        {
                            Id = 2,
                            Apellidos = "Apoyo",
                            DNI = "12345678",
                            Nombres = "Juan",
                            DependenciaId = 2,
                            EsPersonalInterno = true
                        });
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Encargado", b =>
                {
                    b.HasBaseType("Siged.Domain.Entities.Core.Persona");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Oficina")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Encargado");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Apellidos = "Docente Encargada",
                            DNI = "44444444",
                            Nombres = "Maria",
                            Cargo = "Director de Escuela",
                            Oficina = "Pabellón Central"
                        });
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Estudiante", b =>
                {
                    b.HasBaseType("Siged.Domain.Entities.Core.Persona");

                    b.Property<string>("CodigoEstudiante")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("EstaMatriculado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.HasDiscriminator().HasValue("Estudiante");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Apellidos = "Alumno FIIS",
                            DNI = "88888888",
                            Nombres = "Pedro",
                            CodigoEstudiante = "0020210456",
                            EstaMatriculado = true,
                            FechaRegistro = new DateTime(2026, 4, 16, 15, 57, 20, 104, DateTimeKind.Utc).AddTicks(8548)
                        });
                });

            modelBuilder.Entity("PermisoUsuario", b =>
                {
                    b.HasOne("Siged.Domain.Entities.Security.Permiso", null)
                        .WithMany()
                        .HasForeignKey("PermisosEspecialesIdPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Siged.Domain.Entities.Security.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RolPermisos", b =>
                {
                    b.HasOne("Siged.Domain.Entities.Security.Permiso", null)
                        .WithMany()
                        .HasForeignKey("PermisosIdPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Siged.Domain.Entities.Security.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Notice.NewsMedia", b =>
                {
                    b.HasOne("Siged.Domain.Entities.Core.Notice.News", "News")
                        .WithMany("Media")
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("News");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Tournaments.Competition", b =>
                {
                    b.HasOne("Siged.Domain.Entities.Core.Tournaments.Discipline", "Discipline")
                        .WithMany()
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Siged.Domain.Entities.Core.Tournaments.Tournament", "Tournament")
                        .WithMany("Competitions")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Tournaments.DisciplineRule", b =>
                {
                    b.HasOne("Siged.Domain.Entities.Core.Tournaments.Discipline", "Discipline")
                        .WithMany("Rules")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Tournaments.Group", b =>
                {
                    b.HasOne("Siged.Domain.Entities.Core.Tournaments.Phase", "Phase")
                        .WithMany("Groups")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phase");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Tournaments.GroupTeam", b =>
                {
                    b.HasOne("Siged.Domain.Entities.Core.Tournaments.Group", "Group")
                        .WithMany("GroupTeams")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Siged.Domain.Entities.Core.Tournaments.Team", "Team")
                        .WithMany("GroupTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Tournaments.Journal", b =>
                {
                    b.HasOne("Siged.Domain.Entities.Core.Tournaments.Group", "Group")
                        .WithMany("Journals")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Siged.Domain.Entities.Core.Tournaments.Phase", "Phase")
                        .WithMany("Journals")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Phase");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Tournaments.Match", b =>
                {
                    b.HasOne("Siged.Domain.Entities.Core.Tournaments.Discipline", "Discipline")
                        .WithMany()
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Siged.Domain.Entities.Core.Tournaments.Journal", "Journal")
                        .WithMany()
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Siged.Domain.Entities.Core.Tournaments.Team", "LocalTeam")
                        .WithMany()
                        .HasForeignKey("LocalTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Siged.Domain.Entities.Core.Tournaments.Phase", "Phase")
                        .WithMany()
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Siged.Domain.Entities.Core.Tournaments.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId");

                    b.HasOne("Siged.Domain.Entities.Core.Tournaments.Team", "VisitorTeam")
                        .WithMany()
                        .HasForeignKey("VisitorTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("Journal");

                    b.Navigation("LocalTeam");

                    b.Navigation("Phase");

                    b.Navigation("Venue");

                    b.Navigation("VisitorTeam");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Tournaments.MatchEvent", b =>
                {
                    b.HasOne("Siged.Domain.Entities.Core.Tournaments.Match", null)
                        .WithMany("Events")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Siged.Domain.Entities.Core.Tournaments.Player", null)
                        .WithMany("MatchEvents")
                        .HasForeignKey("PlayerId");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Tournaments.Phase", b =>
                {
                    b.HasOne("Siged.Domain.Entities.Core.Tournaments.Competition", "Competition")
                        .WithMany("Phases")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Tournaments.Player", b =>
                {
                    b.HasOne("Siged.Domain.Entities.Core.Tournaments.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Security.UserPreference", b =>
                {
                    b.HasOne("Siged.Domain.Entities.Security.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("Siged.Domain.Entities.Security.UserPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Security.Usuario", b =>
                {
                    b.HasOne("Siged.Domain.Entities.Security.Usuario", "Creador")
                        .WithMany()
                        .HasForeignKey("CreadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Siged.Domain.Entities.Core.Organizacion", "Organizacion")
                        .WithMany("Usuarios")
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Siged.Domain.Entities.Core.Persona", "Persona")
                        .WithOne()
                        .HasForeignKey("Siged.Domain.Entities.Security.Usuario", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Siged.Domain.Entities.Security.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creador");

                    b.Navigation("Organizacion");

                    b.Navigation("Persona");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Administrador", b =>
                {
                    b.HasOne("Siged.Domain.Entities.Core.Dependencia", "Dependencia")
                        .WithMany("Administradores")
                        .HasForeignKey("DependenciaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Dependencia");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Dependencia", b =>
                {
                    b.Navigation("Administradores");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Notice.News", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Organizacion", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Tournaments.Competition", b =>
                {
                    b.Navigation("Phases");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Tournaments.Discipline", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Tournaments.Group", b =>
                {
                    b.Navigation("GroupTeams");

                    b.Navigation("Journals");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Tournaments.Match", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Tournaments.Phase", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Journals");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Tournaments.Player", b =>
                {
                    b.Navigation("MatchEvents");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Tournaments.Team", b =>
                {
                    b.Navigation("GroupTeams");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Tournaments.Tournament", b =>
                {
                    b.Navigation("Competitions");
                });
#pragma warning restore 612, 618
        }
    }
}
