// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Siged.Infrastructure.Persistence;

#nullable disable

namespace Siged.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260306174020_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PermisoUsuario", b =>
                {
                    b.Property<string>("PermisosEspecialesIdPermiso")
                        .HasColumnType("text");

                    b.Property<int>("UsuariosId")
                        .HasColumnType("integer");

                    b.HasKey("PermisosEspecialesIdPermiso", "UsuariosId");

                    b.HasIndex("UsuariosId");

                    b.ToTable("UsuariosPermisos", (string)null);
                });

            modelBuilder.Entity("RolPermisos", b =>
                {
                    b.Property<string>("PermisosIdPermiso")
                        .HasColumnType("text");

                    b.Property<int>("RolesId")
                        .HasColumnType("integer");

                    b.HasKey("PermisosIdPermiso", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("RolPermisos");

                    b.HasData(
                        new
                        {
                            PermisosIdPermiso = "security.user.view",
                            RolesId = 1
                        },
                        new
                        {
                            PermisosIdPermiso = "security.user.view",
                            RolesId = 2
                        },
                        new
                        {
                            PermisosIdPermiso = "security.user.manage",
                            RolesId = 1
                        },
                        new
                        {
                            PermisosIdPermiso = "security.user.manage",
                            RolesId = 2
                        },
                        new
                        {
                            PermisosIdPermiso = "security.role.manage",
                            RolesId = 1
                        },
                        new
                        {
                            PermisosIdPermiso = "core.org.view",
                            RolesId = 1
                        },
                        new
                        {
                            PermisosIdPermiso = "core.org.view",
                            RolesId = 2
                        },
                        new
                        {
                            PermisosIdPermiso = "core.org.view",
                            RolesId = 3
                        },
                        new
                        {
                            PermisosIdPermiso = "core.org.view",
                            RolesId = 4
                        },
                        new
                        {
                            PermisosIdPermiso = "core.org.manage",
                            RolesId = 1
                        },
                        new
                        {
                            PermisosIdPermiso = "comp.tourn.view",
                            RolesId = 1
                        },
                        new
                        {
                            PermisosIdPermiso = "comp.tourn.view",
                            RolesId = 2
                        },
                        new
                        {
                            PermisosIdPermiso = "comp.tourn.view",
                            RolesId = 3
                        },
                        new
                        {
                            PermisosIdPermiso = "comp.tourn.view",
                            RolesId = 4
                        },
                        new
                        {
                            PermisosIdPermiso = "comp.tourn.manage",
                            RolesId = 1
                        },
                        new
                        {
                            PermisosIdPermiso = "comp.tourn.manage",
                            RolesId = 3
                        });
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Dependencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Siglas")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Dependencias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Oficina de Tecnología de Información",
                            Siglas = "OTI"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Rectorado Central",
                            Siglas = "RECT"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Bienestar Universitario",
                            Siglas = "DBU"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Dirección de Admisión",
                            Siglas = "ADM"
                        });
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Organizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abreviatura")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("ColorRepresentativo")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Lema")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PortadaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Facultad");

                    b.HasKey("Id");

                    b.HasIndex("Abreviatura")
                        .IsUnique();

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Organizaciones", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abreviatura = "FIIS",
                            ColorRepresentativo = "#0284c7",
                            EstaActivo = true,
                            Nombre = "Facultad de Ingeniería en Informática y Sistemas",
                            Tipo = "Facultad"
                        },
                        new
                        {
                            Id = 2,
                            Abreviatura = "FZ",
                            ColorRepresentativo = "#d97706",
                            EstaActivo = true,
                            Nombre = "Facultad de Zootecnia",
                            Tipo = "Facultad"
                        },
                        new
                        {
                            Id = 3,
                            Abreviatura = "FA",
                            ColorRepresentativo = "#16a34a",
                            EstaActivo = true,
                            Nombre = "Facultad de Agronomía",
                            Tipo = "Facultad"
                        },
                        new
                        {
                            Id = 4,
                            Abreviatura = "FCEA",
                            ColorRepresentativo = "#9333ea",
                            EstaActivo = true,
                            Nombre = "Facultad de Ciencias Económicas y Administrativas",
                            Tipo = "Facultad"
                        });
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .HasColumnType("text");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("FotoPath")
                        .HasColumnType("text");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DNI")
                        .IsUnique();

                    b.ToTable("Personas", (string)null);

                    b.HasDiscriminator().HasValue("Persona");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Siged.Domain.Entities.Security.Permiso", b =>
                {
                    b.Property<string>("IdPermiso")
                        .HasColumnType("text");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.HasKey("IdPermiso");

                    b.ToTable("Permisos", (string)null);

                    b.HasData(
                        new
                        {
                            IdPermiso = "security.user.view",
                            Categoria = "SEGURIDAD",
                            Descripcion = "Ver lista de usuarios"
                        },
                        new
                        {
                            IdPermiso = "security.user.manage",
                            Categoria = "SEGURIDAD",
                            Descripcion = "Crear y editar usuarios"
                        },
                        new
                        {
                            IdPermiso = "security.role.manage",
                            Categoria = "SEGURIDAD",
                            Descripcion = "Gestionar roles y permisos"
                        },
                        new
                        {
                            IdPermiso = "core.org.view",
                            Categoria = "CORE",
                            Descripcion = "Ver facultades y sedes"
                        },
                        new
                        {
                            IdPermiso = "core.org.manage",
                            Categoria = "CORE",
                            Descripcion = "Administrar facultades"
                        },
                        new
                        {
                            IdPermiso = "comp.tourn.view",
                            Categoria = "COMPETENCIAS",
                            Descripcion = "Ver torneos y resultados"
                        },
                        new
                        {
                            IdPermiso = "comp.tourn.manage",
                            Categoria = "COMPETENCIAS",
                            Descripcion = "Gestionar fechas y torneos"
                        });
                });

            modelBuilder.Entity("Siged.Domain.Entities.Security.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Control total del sistema (OTI)",
                            Nombre = "SuperAdmin"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Personal administrativo de oficinas centrales",
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Docente o administrativo encargado de facultad",
                            Nombre = "Encargado"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Alumno regular de la UNAS",
                            Nombre = "Estudiante"
                        });
                });

            modelBuilder.Entity("Siged.Domain.Entities.Security.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreadoPorUsuarioId")
                        .HasColumnType("integer");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("OrganizacionId")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PersonaId")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiereCambioPassword")
                        .HasColumnType("boolean");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPorUsuarioId");

                    b.HasIndex("OrganizacionId");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstaActivo = true,
                            FechaRegistro = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2a$12$eL7jdgl1iOF508ePe1ScyOrYqdzdDedn1yo5WuGrj1E1.ZovUk0Xe",
                            PersonaId = 1,
                            RequiereCambioPassword = false,
                            RolId = 1,
                            Username = "admin_benjamin"
                        },
                        new
                        {
                            Id = 2,
                            EstaActivo = true,
                            FechaRegistro = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2a$12$eL7jdgl1iOF508ePe1ScyOrYqdzdDedn1yo5WuGrj1E1.ZovUk0Xe",
                            PersonaId = 2,
                            RequiereCambioPassword = true,
                            RolId = 2,
                            Username = "apoyo_juan"
                        });
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Administrador", b =>
                {
                    b.HasBaseType("Siged.Domain.Entities.Core.Persona");

                    b.Property<int?>("DependenciaId")
                        .HasColumnType("integer");

                    b.Property<bool>("EsPersonalInterno")
                        .HasColumnType("boolean");

                    b.HasIndex("DependenciaId");

                    b.HasDiscriminator().HasValue("Administrador");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellidos = "Admin",
                            DNI = "76063362",
                            Nombres = "Benjamín",
                            DependenciaId = 1,
                            EsPersonalInterno = true
                        },
                        new
                        {
                            Id = 2,
                            Apellidos = "Apoyo",
                            DNI = "12345678",
                            Nombres = "Juan",
                            DependenciaId = 2,
                            EsPersonalInterno = true
                        });
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Encargado", b =>
                {
                    b.HasBaseType("Siged.Domain.Entities.Core.Persona");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Oficina")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Encargado");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Estudiante", b =>
                {
                    b.HasBaseType("Siged.Domain.Entities.Core.Persona");

                    b.Property<string>("CodigoEstudiante")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("EstaMatriculado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.HasDiscriminator().HasValue("Estudiante");
                });

            modelBuilder.Entity("PermisoUsuario", b =>
                {
                    b.HasOne("Siged.Domain.Entities.Security.Permiso", null)
                        .WithMany()
                        .HasForeignKey("PermisosEspecialesIdPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Siged.Domain.Entities.Security.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RolPermisos", b =>
                {
                    b.HasOne("Siged.Domain.Entities.Security.Permiso", null)
                        .WithMany()
                        .HasForeignKey("PermisosIdPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Siged.Domain.Entities.Security.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Siged.Domain.Entities.Security.Usuario", b =>
                {
                    b.HasOne("Siged.Domain.Entities.Security.Usuario", "Creador")
                        .WithMany()
                        .HasForeignKey("CreadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Siged.Domain.Entities.Core.Organizacion", "Organizacion")
                        .WithMany("Usuarios")
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Siged.Domain.Entities.Core.Persona", "Persona")
                        .WithOne()
                        .HasForeignKey("Siged.Domain.Entities.Security.Usuario", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Siged.Domain.Entities.Security.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creador");

                    b.Navigation("Organizacion");

                    b.Navigation("Persona");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Administrador", b =>
                {
                    b.HasOne("Siged.Domain.Entities.Core.Dependencia", "Dependencia")
                        .WithMany("Administradores")
                        .HasForeignKey("DependenciaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Dependencia");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Dependencia", b =>
                {
                    b.Navigation("Administradores");
                });

            modelBuilder.Entity("Siged.Domain.Entities.Core.Organizacion", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
